/*
Analytical question:
Identify zones with the highest number of taxi pickups.

Source mart:
nyc_taxi.gold_location_pair_stats

Source grain:
One row represents aggregated route statistics by:
- pickup_date
- trip_type
- pickup_location_id
- dropoff_location_id

Methodology:
1. Aggregate the route-level mart to the pickup zone level.
2. Group by pickup_borough and pickup_zone.
3. Sum trips_count to get total pickup demand for each zone.
4. Sum total_revenue to estimate total revenue generated by pickups from each zone.
5. Calculate avg_check as a weighted average:
   total_revenue_sum / trips_count_sum

Why weighted average:
Using avg(avg_check) would be misleading because low-volume and high-volume routes
would have the same weight. Weighted average gives more influence to routes with
more trips.

Implementation note:
The aggregation is calculated in a subquery first. The outer query calculates
derived metrics and rounding. This avoids nested aggregate expressions and
ClickHouse alias substitution issues.

Limitations:
This query measures pickup demand concentration. It does not directly explain
passenger intent or trip purpose.
*/

SELECT
    pickup_borough,
    pickup_zone,
    trips_count_sum AS trips_count,
    round(total_revenue_sum, 2) AS total_revenue,
    round(total_revenue_sum / trips_count_sum, 2) AS avg_check
FROM
(
    SELECT
        pickup_borough,
        pickup_zone,
        sum(trips_count) AS trips_count_sum,
        sum(total_revenue) AS total_revenue_sum
    FROM nyc_taxi.gold_location_pair_stats
    WHERE pickup_zone IS NOT NULL
      AND notEmpty(pickup_zone)
    GROUP BY
        pickup_borough,
        pickup_zone
)
ORDER BY trips_count DESC
LIMIT 20