/*
Analytical question:
Identify peak taxi demand hours.

Source mart:
nyc_taxi.gold_hourly_trips

Source grain:
One row represents aggregated hourly trip statistics by:
- pickup_date
- pickup_hour
- trip_type

Methodology:
1. Aggregate the hourly gold mart to the pickup_hour level.
2. Group by pickup_hour.
3. Sum trips_count to calculate total demand for each hour of day.
4. Sum total_revenue to calculate total revenue generated by each hour.
5. Calculate avg_check as a weighted average:
   total_revenue_sum / trips_count_sum
6. Calculate weighted average trip distance:
   sum(avg_trip_distance * trips_count) / sum(trips_count)
7. Calculate weighted average trip duration:
   sum(avg_trip_duration_minutes * trips_count) / sum(trips_count)
8. Calculate each hour's share of total trips:
   trips_count_sum / total_trips * 100

Why weighted averages:
The source mart is already aggregated by date, hour, and trip type.
Using avg(avg_check), avg(avg_trip_distance), or avg(avg_trip_duration_minutes)
would incorrectly give the same weight to low-volume and high-volume hourly groups.

Limitations:
This query identifies peak hours by total trip volume across the full year.
It does not separate weekdays from weekends and does not explain the reason for demand peaks.
*/

WITH
hourly AS
(
    SELECT
        pickup_hour,
        sum(trips_count) AS trips_count_sum,
        sum(total_revenue) AS total_revenue_sum,
        sum(avg_trip_distance * trips_count) AS weighted_trip_distance_sum,
        sum(avg_trip_duration_minutes * trips_count) AS weighted_trip_duration_sum
    FROM nyc_taxi.gold_hourly_trips
    GROUP BY pickup_hour
),
total AS
(
    SELECT
        sum(trips_count_sum) AS total_trips
    FROM hourly
)
SELECT
    hourly.pickup_hour,
    hourly.trips_count_sum AS trips_count,
    round(hourly.trips_count_sum / total.total_trips * 100, 2) AS trips_share_pct,
    round(hourly.total_revenue_sum, 2) AS total_revenue,
    round(hourly.total_revenue_sum / hourly.trips_count_sum, 2) AS avg_check,
    round(hourly.weighted_trip_distance_sum / hourly.trips_count_sum, 2) AS avg_trip_distance,
    round(hourly.weighted_trip_duration_sum / hourly.trips_count_sum, 2) AS avg_trip_duration_minutes
FROM hourly
CROSS JOIN total
ORDER BY trips_count DESC
LIMIT 24