/*
Analytical question:
Analyze trip distribution by trip type and infer possible passenger behavior patterns.

Source mart:
nyc_taxi.gold_hourly_trips

Source grain:
One row represents aggregated hourly trip statistics by:
- pickup_date
- pickup_hour
- trip_type

Methodology:
1. Aggregate the hourly gold mart to the trip_type level.
2. Group by trip_type.
3. Sum trips_count to calculate total demand for each trip type.
4. Sum total_revenue to calculate total revenue generated by each trip type.
5. Calculate each trip type's share of total trips:
   trip_type_trips_count / total_trips_count * 100
6. Calculate avg_check as a weighted average:
   total_revenue_sum / trips_count_sum
7. Calculate weighted average trip distance:
   sum(avg_trip_distance * trips_count) / sum(trips_count)
8. Calculate weighted average trip duration:
   sum(avg_trip_duration_minutes * trips_count) / sum(trips_count)
9. Estimate total distance:
   sum(avg_trip_distance * trips_count)
10. Calculate average passenger cost per mile:
   total_revenue_sum / estimated_total_distance

Why weighted averages:
The source mart is already aggregated by date, hour, and trip type.
Using simple averages such as avg(avg_check), avg(avg_trip_distance), or
avg(avg_trip_duration_minutes) would incorrectly give the same weight to
low-volume and high-volume hourly groups.

Why cost per mile is estimated:
The source mart does not store total trip distance directly.
It stores avg_trip_distance and trips_count for each aggregated group.
Therefore, total distance is estimated as:
avg_trip_distance * trips_count

Business interpretation:
The dataset does not contain an explicit passenger intent field.
Therefore, passenger motives are inferred indirectly from trip type, average
distance, average duration, average check, cost per mile, and demand share.

Limitations:
Trip type is a proxy based on trip distance. It helps interpret behavior patterns,
but it does not directly identify the true passenger purpose.
Cost per mile is calculated from aggregated gold mart metrics, so it is an
estimated weighted metric rather than a row-level calculation from raw trips.
*/

WITH
trip_type_stats AS
(
    SELECT
        trip_type,
        sum(trips_count) AS trips_count_sum,
        sum(total_revenue) AS total_revenue_sum,
        sum(avg_trip_distance * trips_count) AS estimated_total_distance_sum,
        sum(avg_trip_duration_minutes * trips_count) AS weighted_trip_duration_sum
    FROM nyc_taxi.gold_hourly_trips
    WHERE trip_type IS NOT NULL
      AND notEmpty(trip_type)
    GROUP BY trip_type
),
total AS
(
    SELECT
        sum(trips_count_sum) AS total_trips
    FROM trip_type_stats
)
SELECT
    trip_type,
    trips_count_sum AS trips_count,
    round(trips_count_sum / total.total_trips * 100, 2) AS trips_share_pct,
    round(total_revenue_sum, 2) AS total_revenue,
    round(total_revenue_sum / trips_count_sum, 2) AS avg_check,
    round(estimated_total_distance_sum / trips_count_sum, 2) AS avg_trip_distance,
    round(weighted_trip_duration_sum / trips_count_sum, 2) AS avg_trip_duration_minutes,
    round(total_revenue_sum / estimated_total_distance_sum, 2) AS avg_cost_per_mile
FROM trip_type_stats
CROSS JOIN total
ORDER BY trips_count DESC